title: George Baker
email: georgestephenbaker@icloud.com
author: George Baker

description: >
  Ruby on Rails developer based in the UK

url: https://gsbaker.github.io

timezone: Europe/Belfast

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-sass-converter

jekyll_compose:
  post_default_front_matter:
    last_modified_at:
    permalink:
    description:
    image:
    published: true
    sitemap: true
    excerpt_separator: <!--more-->
    categories:
    tags:
