title: George Baker
author:
  name: George Baker
  email: george@gsbaker.uk
description: > # this means to ignore newlines until "show_excerpts:"
  I am a computer science student with a diverse range of interests. The goal of my blog is to provide original,
  thoughtful, and well-researched content.
url: https://www.gsbaker.uk
# date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d-%m-%Y"

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
