title: gsbaker

author:
  name: George Baker
  email: george@gsbaker.uk

description: Curiositas Est Scientia

url: https://gsbaker.github.io
# date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d-%m-%Y"

timezone: Europe/Belfast

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

jekyll_compose:
  post_default_front_matter:
    last_modified_at:
    permalink:
    description:
    image:
    published: true
    sitemap: true
    excerpt_separator: <!--more-->
    categories:
    tags: