title: Curious George
author:
  name: George Baker
  email: george@gsbaker.uk
description: > # this means to ignore newlines until "show_excerpts:"
  My name is George and I created this blog to document my life journey. I try to write weekly notes about what's
  going on in my life, and the world around me.
url: https://www.gsbaker.uk
# date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d-%m-%Y"

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
