title: Curious George
author:
  name: George Baker
  email: george@gsbaker.uk
description: > # this means to ignore newlines until "show_excerpts:"
  Curious George is a blog written by George Baker: a software engineer who loves problem solving
  and creativity.
url: https://gsbaker.github.io
# date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%d-%m-%Y"

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
